### PR TITLE
Added check for call constructor without parameters

### PR DESCRIPTION
**Pull request by objNameGit**
Added check for calling the constructor without parameters. If the constructor has no arguments, an error is thrown

### CODE REVIEW

**Comment by objNameGit** [comment]
no problem, I will do everything as it should be. and add to this PR

**Comment by objNameGit** [comment]
I noticed that you do not have a file package-lock.js
maybe it's worth adding his repository?

**Comment by lucianoratamero** [comment]
I personally never rely on package-lock.json, but for a library, it makes sense to add one. if you want to open an issue for that or just solve it in this PR, go ahead, @objNameGit ! :D

**Comment by lucianoratamero** [comment]
@PoojaKhandhadia addresses the package-lock.json issue on their PR, so I'm merging this and theirs as well

**Pull request merged**
